# -*- coding: utf-8 -*-
"""analysis.R

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-dnFu8CCI6-G2k1Xu_l3Li_5m992PDX
"""

if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

# DATA ACQUISITION
# dataset from TidyTuesday repository
url <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-22/prison_population.csv"
raw_data <- read_csv(url)

# 3. Clean Data
# Focusing on the 1990-2015 window to observe the peak of the 'tough on crime' era
prison_trends <- raw_data %>%
  filter(year >= 1990 & year <= 2015) %>%
  group_by(year) %>%
  summarize(
    total_prison_pop = sum(prison_population, na.rm = TRUE),
    total_general_pop = sum(population, na.rm = TRUE)
  ) %>%
  mutate(rate_per_100k = (total_prison_pop / total_general_pop) * 100000)

# 4. Statistical Modeling
# Use a linear model to analyze the overall progression over time.
trend_model <- lm(rate_per_100k ~ year, data = prison_trends)
print(summary(trend_model))

# 5. Vizualization
# Identifying the 2008 'turning point' often associated with the Great Recession
# and subsequent shifts toward criminal justice reform.
trend_plot <- ggplot(prison_trends, aes(x = year, y = rate_per_100k)) +
  geom_line(color = "#2c3e50", linewidth = 1.2) +
  geom_point(color = "#e74c3c", size = 2) +
  geom_vline(xintercept = 2008, linetype = "dashed", color = "darkgrey") +
  annotate("text", x = 2006, y = max(prison_trends$rate_per_100k),
           label = "2008 Policy Shift", angle = 90, vjust = -0.5) +
  labs(
    title = "U.S. Incarceration Rates (1990-2015)",
    subtitle = "Analysis of longitudinal trends in legal system outcomes",
    x = "Year",
    y = "Prisoners per 100,000 Residents",
    caption = "Data Source: TidyTuesday / Vera Institute"
  ) +
  theme_minimal()

# Display plot
print(trend_plot)

# Save output
ggsave("incarceration_trend_plot.png", plot = trend_plot, width = 8, height = 5)